# Generated by Django 4.2.7 on 2023-11-27 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='average_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
